### PR TITLE
Initial helm charts for MDN

### PR DESCRIPTION
**Pull request by escattone**
This is still a work-in-progress, but I think it's in a state such that it would be useful to have more eyes on it.

### CODE REVIEW

**Comment by jwhitlock** [comment]
@escattone mentioned he needs a reviewer for this.  I'm 👍 based on what I saw in Toronto, especially since a merge doesn't mean we have to use it yet, just populates the repo.  I'm far enough behind on Kubernetes, etc. that I'm punting to @jgmize and @metadave for a deeper review.

**Comment by bookshelfdave** [comment]
- we might want to take a look at the limites/requests across the entire app to ensure that k8s can allocate enough resources across the cluster. I see that elasticsearch sets requests/limits to 1 cpu and 2GB, which seems ok, but Java eats memory... should the limit be higher with a lower request etc?
- we should set some basic policies for `imagePullPolicy` for each deployment, as the `latest` tag may not always pull.
- in the near future, MySQL Persistent Volume Claim should be backed by EBS (looks like persistence is disabled by default)
- nice use of secrets for mysql ;-)

Given that helm seems to Make Things More Complicated, should we ever consider dropping all the templates for all MDN services into a single chart similar to how we [deploy demo instances](https://github.com/mozilla/kuma/tree/master/k8s)

I'm 👍 on whats here, nice work @escattone!

**Review by bookshelfdave — APPROVED** [review]

**Comment by escattone** [comment]
Thanks for taking a look @jwhitlock and @metadave ! I'm not sure we'll ever use these charts, but it's a starting point for experimentation. Thanks for the review points @metadave, all great points except that I deserve no praise for the "nice use of secrets" in the mysql chart, as it's a copy from the stable repo of charts (I wanted the stable mysql chart but also wanted to use our own image with the custom collation baked in) 😃 .

**Review by jgmize — COMMENTED** [review]
+1 nice work @escattone!

**Pull request merged**
